'use client'

import { createContext, useContext, useEffect, useState } from 'react'
import type { Language } from '@/types'

const translations = {
  he: {
    appName: 'GROWTH',
    tagline: 'הצמיחה האישית שלך',
    login: 'התחברות',
    signup: 'הרשמה',
    email: 'אימייל',
    password: 'סיסמה',
    fullName: 'שם מלא',
    loginTitle: 'ברוך הבא',
    signupTitle: 'הצטרף ל‑GROWTH',
    noAccount: 'אין לך חשבון?',
    hasAccount: 'יש לך חשבון?',
    forgotPassword: 'שכחת סיסמה?',
    forgotPasswordTitle: 'איפוס סיסמה',
    forgotPasswordDesc: 'הכנס את האימייל שלך ונשלח לך קישור לאיפוס הסיסמה.',
    sendResetLink: 'שלח קישור איפוס',
    resetEmailSent: 'המייל נשלח!',
    resetEmailSentDesc: 'בדוק את תיבת המייל שלך – שלחנו לך קישור לאיפוס הסיסמה.',
    backToLogin: 'חזרה להתחברות',
    resetPasswordTitle: 'סיסמה חדשה',
    resetPasswordLoading: 'מאמת את הקישור...',
    newPassword: 'סיסמה חדשה',
    confirmPassword: 'אימות סיסמה',
    updatePassword: 'עדכן סיסמה',
    passwordsNoMatch: 'הסיסמאות לא תואמות',
    passwordTooShort: 'הסיסמה חייבת להכיל לפחות 6 תווים',
    today: 'היום',
    habits: 'הרגלים',
    domains: 'תחומים',
    streak: 'רצף',
    days: 'ימים',
    progress: 'התקדמות',
    addHabit: 'הוסף הרגל',
    complete: 'סמן כהשלמה',
    completed: 'הושלם',
    goodMorning: 'בוקר טוב',
    goodAfternoon: 'צהריים טובים',
    goodEvening: 'ערב טוב',
    goodNight: 'לילה טוב',
    noHabitsYet: 'עדיין אין הרגלים — הוסף הרגל ראשון',
    back: 'חזרה',
    myProgress: 'ההתקדמות שלי',
    settings: 'הגדרות',
    language: 'שפה',
    logout: 'התנתקות',
    habitName: 'שם ההרגל',
    save: 'שמור',
    cancel: 'ביטול',
    deleteHabit: 'מחק הרגל',
    deleteConfirm: 'בטוח?',
    todayHabits: 'הרגלי היום',
    allDomains: 'כל התחומים',
    // Torah workspace
    torahWorkspace: 'אזור קודש',
    torahHome: 'בית',
    torahLearn: 'לימוד',
    torahFeed: 'פיד',
    torahSummaries: 'סיכומים',
    torahProfile: 'פרופיל',
    continuelearning: 'המשך לימוד',
    startLearning: 'התחל שיעור',
    minutesToday: 'דקות היום',
    sessionsToday: 'שיעורים היום',
    totalHours: 'שעות סה"כ',
    totalSessions: 'שיעורים סה"כ',
    totalSummaries: 'סיכומים',
    whatLearning: 'מה אתה לומד?',
    textReference: 'מקור (למשל: ברכות ב:א)',
    addNote: 'הוסף הערה',
    addQuestion: 'הוסף שאלה',
    endSession: 'סיים שיעור',
    sessionSaved: 'שיעור נשמר',
    recentSessions: 'שיעורים אחרונים',
    noSessionsYet: 'עדיין אין שיעורים',
    newSummary: 'סיכום חדש',
    editSummary: 'ערוך סיכום',
    summaryTitle: 'כותרת',
    summaryContent: 'תוכן',
    summarySource: 'מקור',
    summaryFolder: 'תיקייה',
    summaryTags: 'תגיות (מופרדות בפסיקים)',
    noSummariesYet: 'עדיין אין סיכומים',
    favorites: 'מועדפים',
    allFolders: 'הכל',
    search: 'חיפוש',
    lessonFeed: 'שיעורים',
    savelesson: 'שמור',
    saved: 'נשמר',
    duration: 'משך',
    speaker: 'מגיד',
    learningStats: 'סטטיסטיקות',
    weeklyLearning: 'לימוד שבועי',
    habitPerformance: 'ביצוע הרגלים',
    gemara: 'גמרא',
    mishnah: 'משנה',
    tanakh: 'תנ"ך',
    halacha: 'הלכה',
    article: 'מאמר',
    other: 'אחר',
    min: 'דק',
    notes: 'הערות',
    questions: 'שאלות',
    sessionTimer: 'טיימר שיעור',
    running: 'רץ',
    paused: 'מושהה',
    setReminder: 'הגדר תזכורת',
    reminderNotification: 'התראה',
    reminderAlarm: 'אזעקה',
    deleteReminder: 'מחק תזכורת',
    habitReminderBody: 'זמן לבצע את ההרגל! 💪',
    remindersSection: 'תזכורות',
    notificationPermission: 'הרשאת התראות',
    permissionGranted: 'מאושר ✓',
    permissionDenied: 'נדחה ✗',
    permissionPending: 'לא הוגדר',
    enableNotifications: 'הפעל התראות',
    nightCheckinReminder: 'תזכורת לצ׳ק-אין לילה',
    journalReminder: 'תזכורת ליומן',
    readingReminder: 'תזכורת לקריאה',
    noReminder: 'ללא תזכורת',
    reminderTimeLabel: 'שעת תזכורת',
    // Book links
    linkToBook: 'קשר לספר',
    linkedSummaries: 'סיכומים מקושרים',
    noLinkedSummaries: 'אין סיכומים מקושרים',
    saveFirstToLink: 'שמור כדי לקשר לספר',
    noBooksToLink: 'אין ספרים. הוסף ספר באזור הקריאה',
    detach: 'הסר קישור',
    openSource: 'פתח',
    untitled: 'ללא כותרת',
    // Errors & feedback
    somethingWrong: 'משהו השתבש',
    errorBody: 'אירעה שגיאה לא צפויה. נסה שוב.',
    tryAgain: 'נסה שוב',
    notFoundTitle: 'הדף לא נמצא',
    notFoundBody: 'הדף שחיפשת לא קיים.',
    goHome: 'חזרה לדף הבית',
    saveFailed: 'השמירה נכשלה — נסה שוב',
    loadFailed: 'הטעינה נכשלה — נסה שוב',
    close: 'סגור',
    // Quick add habit
    quickAddHabit: 'הוספת הרגל',
    chooseDomain: 'בחר תחום',
    habitTimeOptional: 'שעה (אופציונלי)',
    adding: 'מוסיף...',
    // Habit scheduling
    everyDay: 'כל יום',
    specificDays: 'ימים ספציפים',
    dayShortSun: 'ר׳',
    dayShortMon: 'ב׳',
    dayShortTue: 'ג׳',
    dayShortWed: 'ד׳',
    dayShortThu: 'ה׳',
    dayShortFri: 'ו׳',
    dayShortSat: 'ש׳',
    // Onboarding
    onbWelcomeTitle: 'ברוך הבא ל‑GROWTH',
    onbWelcomeBody: 'בוא נבנה יחד את הצמיחה האישית שלך בכמה צעדים קצרים.',
    onbDomainsTitle: 'בחר את תחומי החיים שלך',
    onbDomainsBody: 'בחר את התחומים שחשובים לך. תוכל להוסיף ולשנות אחר כך.',
    onbHabitsTitle: 'בחר הרגלים להתחלה',
    onbHabitsBody: 'בחר כמה הרגלים שתרצה להתחיל לעקוב אחריהם. תמיד אפשר להוסיף עוד.',
    onbNext: 'הבא',
    onbSkip: 'דלג',
    onbFinish: 'בוא נתחיל',
    onbAdded: 'נוסף',
    // Empty states
    emptyHabitsTitle: 'עדיין לא הוספת הרגלים',
    emptyHabitsBody: 'התחל מאחד מאלה, או הוסף הרגל משלך:',
    emptyJournalTitle: 'היומן שלך ריק',
    emptyJournalBody: 'התחל לכתוב את המחשבות שלך.',
    suggestionsLabel: 'הצעות',
    // Schedule
    activityName: 'שם הפעילות',
    resetSchedule: 'שחזר לוח ברירת מחדל',
    resetScheduleConfirm: 'לשחזר את הלוח המקורי? שינויים שביצעת יימחקו.',
    // Settings — profile
    profile: 'פרופיל',
    editName: 'ערוך שם',
    namePlaceholder: 'השם שלך',
    memberSince: 'חבר מאז',
    longestStreak: 'שיא רצף',
    changePhoto: 'שנה תמונה',
    uploadingPhoto: 'מעלה...',
    photoUpdated: 'תמונה עודכנה',
    photoError: 'שגיאה בהעלאת התמונה',
    nameSaved: 'שם נשמר',
    // Settings — data
    exportData: 'ייצוא נתונים',
    exportHabits: 'ייצוא הרגלים (CSV)',
    exportJournal: 'ייצוא יומן (CSV)',
    exporting: 'מייצא...',
    exportDone: 'הורד בהצלחה',
    // Settings — account
    account: 'חשבון',
    deleteAccount: 'מחק חשבון',
    deleteAccountConfirm: 'פעולה זו בלתי הפיכה. כל הנתונים יימחקו לצמיתות.',
    typeToConfirm: 'הקלד "מחק" לאישור',
    deleting: 'מוחק...',
    deleteSuccess: 'החשבון נמחק',
    // Sync overview
    noItemsForPeriod: 'אין פריטים לתקופה זו',
  },
  en: {
    appName: 'GROWTH',
    tagline: 'Your personal growth journey',
    login: 'Login',
    signup: 'Sign Up',
    email: 'Email',
    password: 'Password',
    fullName: 'Full Name',
    loginTitle: 'Welcome back',
    signupTitle: 'Join GROWTH',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    forgotPassword: 'Forgot password?',
    forgotPasswordTitle: 'Reset password',
    forgotPasswordDesc: 'Enter your email and we\'ll send you a reset link.',
    sendResetLink: 'Send reset link',
    resetEmailSent: 'Email sent!',
    resetEmailSentDesc: 'Check your inbox — we sent you a password reset link.',
    backToLogin: 'Back to',
    resetPasswordTitle: 'New password',
    resetPasswordLoading: 'Verifying link...',
    newPassword: 'New password',
    confirmPassword: 'Confirm password',
    updatePassword: 'Update password',
    passwordsNoMatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    today: 'Today',
    habits: 'Habits',
    domains: 'Domains',
    streak: 'Streak',
    days: 'days',
    progress: 'Progress',
    addHabit: 'Add Habit',
    complete: 'Mark Complete',
    completed: 'Completed',
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    goodNight: 'Good night',
    noHabitsYet: 'No habits yet — add your first habit',
    back: 'Back',
    myProgress: 'My Progress',
    settings: 'Settings',
    language: 'Language',
    logout: 'Logout',
    habitName: 'Habit name',
    save: 'Save',
    cancel: 'Cancel',
    deleteHabit: 'Delete habit',
    deleteConfirm: 'Sure?',
    todayHabits: "Today's Habits",
    allDomains: 'All Domains',
    // Torah workspace
    torahWorkspace: 'Torah Workspace',
    torahHome: 'Home',
    torahLearn: 'Learn',
    torahFeed: 'Feed',
    torahSummaries: 'Summaries',
    torahProfile: 'Profile',
    continuelearning: 'Continue Learning',
    startLearning: 'Start Session',
    minutesToday: 'Minutes Today',
    sessionsToday: 'Sessions Today',
    totalHours: 'Total Hours',
    totalSessions: 'Total Sessions',
    totalSummaries: 'Summaries',
    whatLearning: 'What are you learning?',
    textReference: 'Reference (e.g. Berakhot 2a)',
    addNote: 'Add note',
    addQuestion: 'Add question',
    endSession: 'End Session',
    sessionSaved: 'Session saved',
    recentSessions: 'Recent Sessions',
    noSessionsYet: 'No sessions yet',
    newSummary: 'New Summary',
    editSummary: 'Edit Summary',
    summaryTitle: 'Title',
    summaryContent: 'Content',
    summarySource: 'Source',
    summaryFolder: 'Folder',
    summaryTags: 'Tags (comma separated)',
    noSummariesYet: 'No summaries yet',
    favorites: 'Favorites',
    allFolders: 'All',
    search: 'Search',
    lessonFeed: 'Lessons',
    savelesson: 'Save',
    saved: 'Saved',
    duration: 'Duration',
    speaker: 'Speaker',
    learningStats: 'Statistics',
    weeklyLearning: 'Weekly Learning',
    habitPerformance: 'Habit Performance',
    gemara: 'Gemara',
    mishnah: 'Mishnah',
    tanakh: 'Tanakh',
    halacha: 'Halacha',
    article: 'Article',
    other: 'Other',
    min: 'min',
    notes: 'Notes',
    questions: 'Questions',
    sessionTimer: 'Session Timer',
    running: 'Running',
    paused: 'Paused',
    setReminder: 'Set reminder',
    reminderNotification: 'Notification',
    reminderAlarm: 'Alarm',
    deleteReminder: 'Delete reminder',
    habitReminderBody: "Time to complete your habit! 💪",
    remindersSection: 'Reminders',
    notificationPermission: 'Notification Permission',
    permissionGranted: 'Granted ✓',
    permissionDenied: 'Denied ✗',
    permissionPending: 'Not set',
    enableNotifications: 'Enable Notifications',
    nightCheckinReminder: 'Night check-in reminder',
    journalReminder: 'Journal reminder',
    readingReminder: 'Reading reminder',
    noReminder: 'No reminder',
    reminderTimeLabel: 'Reminder time',
    // Book links
    linkToBook: 'Link to book',
    linkedSummaries: 'Linked summaries',
    noLinkedSummaries: 'No linked summaries yet',
    saveFirstToLink: 'Save first to link',
    noBooksToLink: 'No books yet. Add one in Reading',
    detach: 'Unlink',
    openSource: 'Open',
    untitled: 'Untitled',
    // Errors & feedback
    somethingWrong: 'Something went wrong',
    errorBody: 'An unexpected error occurred. Please try again.',
    tryAgain: 'Try again',
    notFoundTitle: 'Page not found',
    notFoundBody: "The page you're looking for doesn't exist.",
    goHome: 'Back to home',
    saveFailed: 'Save failed — try again',
    loadFailed: 'Loading failed — try again',
    close: 'Close',
    // Quick add habit
    quickAddHabit: 'Add habit',
    chooseDomain: 'Choose a domain',
    habitTimeOptional: 'Time (optional)',
    adding: 'Adding...',
    // Habit scheduling
    everyDay: 'Every day',
    specificDays: 'Specific days',
    dayShortSun: 'Sun',
    dayShortMon: 'Mon',
    dayShortTue: 'Tue',
    dayShortWed: 'Wed',
    dayShortThu: 'Thu',
    dayShortFri: 'Fri',
    dayShortSat: 'Sat',
    // Onboarding
    onbWelcomeTitle: 'Welcome to GROWTH',
    onbWelcomeBody: "Let's build your personal growth in a few short steps.",
    onbDomainsTitle: 'Choose your life domains',
    onbDomainsBody: 'Pick the domains that matter to you. You can always add or change them later.',
    onbHabitsTitle: 'Pick habits to start',
    onbHabitsBody: 'Choose a few habits to start tracking. You can always add more.',
    onbNext: 'Next',
    onbSkip: 'Skip',
    onbFinish: "Let's go",
    onbAdded: 'Added',
    // Empty states
    emptyHabitsTitle: "You haven't added any habits yet",
    emptyHabitsBody: 'Start with one of these, or add your own:',
    emptyJournalTitle: 'Your journal is empty',
    emptyJournalBody: 'Start writing your thoughts.',
    suggestionsLabel: 'Suggestions',
    // Schedule
    activityName: 'Activity name',
    resetSchedule: 'Reset to default schedule',
    resetScheduleConfirm: 'Reset to the original schedule? Your changes will be lost.',
    // Settings — profile
    profile: 'Profile',
    editName: 'Edit name',
    namePlaceholder: 'Your name',
    memberSince: 'Member since',
    longestStreak: 'Longest streak',
    changePhoto: 'Change photo',
    uploadingPhoto: 'Uploading...',
    photoUpdated: 'Photo updated',
    photoError: 'Photo upload failed',
    nameSaved: 'Name saved',
    // Settings — data
    exportData: 'Export data',
    exportHabits: 'Export habits (CSV)',
    exportJournal: 'Export journal (CSV)',
    exporting: 'Exporting...',
    exportDone: 'Downloaded',
    // Settings — account
    account: 'Account',
    deleteAccount: 'Delete account',
    deleteAccountConfirm: 'This action is irreversible. All your data will be permanently deleted.',
    typeToConfirm: 'Type "delete" to confirm',
    deleting: 'Deleting...',
    deleteSuccess: 'Account deleted',
    // Sync overview
    noItemsForPeriod: 'No items for this period',
  },
}

export type TranslationKey = keyof typeof translations.he

interface LangContextType {
  lang: Language
  t: (key: TranslationKey) => string
  toggleLang: () => void
  isRTL: boolean
}

const LangContext = createContext<LangContextType>({
  lang: 'en',
  t: (key) => key,
  toggleLang: () => {},
  isRTL: false,
})

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>('en')

  useEffect(() => {
    const saved = localStorage.getItem('growth-lang') as Language | null
    // eslint-disable-next-line react-hooks/set-state-in-effect -- localStorage is SSR-unsafe, must sync post-mount
    if (saved === 'en' || saved === 'he') setLang(saved)
  }, [])

  useEffect(() => {
    document.documentElement.dir = lang === 'he' ? 'rtl' : 'ltr'
    document.documentElement.lang = lang
    localStorage.setItem('growth-lang', lang)
  }, [lang])

  const toggleLang = () => setLang((prev) => (prev === 'he' ? 'en' : 'he'))
  const t = (key: TranslationKey) => translations[lang][key]
  const isRTL = lang === 'he'

  return (
    <LangContext.Provider value={{ lang, t, toggleLang, isRTL }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
